# Generated by Django 5.1.6 on 2025-02-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
