# Generated by Django 5.1.6 on 2025-02-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bid',
            field=models.CharField(default='', editable=False, max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pid',
            field=models.CharField(default='9e970dd21d', editable=False, max_length=13, primary_key=True, serialize=False),
        ),
    ]
