# Generated by Django 5.1.6 on 2025-03-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_customuser_birth_date_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ชาย'), ('female', 'หญิง'), ('other', 'อื่นๆ')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'ลูกค้า'), ('employee', 'พนักงาน'), ('admin', 'ผู้ดูแลระบบ')], default='customer', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pid',
            field=models.CharField(default='8e8a93f5e6', editable=False, max_length=13, primary_key=True, serialize=False),
        ),
    ]
