# Generated by Django 5.1.6 on 2025-03-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_alter_customuser_gender_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pid',
            field=models.CharField(default='4f13b8aff7', editable=False, max_length=13, primary_key=True, serialize=False),
        ),
    ]
